### ISSUE TITLE
can you give some advice on how to build the dataset?

### ISSUE THREAD

**Issue by von1000** [thunlp/IKRL#2]
Hi! I'm trying to build the dataset according to the "image_list" you shared, but I'm in trouble getting all these data. I was planning to delete images in ILSVRC 2012 dataset, but there are only 1000 synsets in ILSVRC, which is far less than yours. I also considered downloading images from imagenet directly, but many links are invalid now. So, can you give me some advice on how to build the dataset? Thanks in advance!

**Comment by von1000** [comment]
I figured that out just after posting the question. Sorry bothering!

**Comment by flow3rdown** [comment]
> I figured that out just after posting the question. Sorry bothering!

Hi, Have you found the image data? Can you give me some suggestions？
